### ISSUE TITLE
Pylint-File-Header doesn't work with Pylint 3.0

### ISSUE THREAD

**Issue by chlafreniere** [HaaLeo/pylint-file-header#6]
| Python Version | Pylint Version | pylintfileheader Version |
| -------------- | -------------- | ------------------------ |
|       3.9         |         3.0.0       |             0.3.2             |

# Description
Given pylint's [3.0.0 release](https://github.com/pylint-dev/pylint/releases/tag/v3.0.0), IRawChecker was removed (I believe in [this](https://github.com/pylint-dev/pylint/pull/8404/) PR)

## Expected Behavior
When running pylint, all imports succeed

## Actual Behavior
  ```File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pylintfileheader/__init__.py", line 9, in <module>
    from pylintfileheader import plugin, file_header_checker  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pylintfileheader/plugin.py", line 10, in <module>
    from pylintfileheader.file_header_checker import FileHeaderChecker
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pylintfileheader/file_header_checker.py", line 9, in <module>
    from pylint.interfaces import IRawChecker
ImportError: cannot import name 'IRawChecker' from 'pylint.interfaces' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pylint/interfaces.py)```


# Steps to Reproduce
<!-- Please add here all necessary steps that need to be taken to reproduce the behavior. -->
1. Install pylint (v3.0.0)
2. Install pylintfileheader
3. Run pylint
4. ImportError occurs

</code></pre></details>

**Comment by HaaLeo** [comment]
Hi @chlafreniere thx for reporting this issue. I'll happily accept a PR for this. Right now I cannot estimate when I'll find time to fix this on my own to support pylint@3

**Comment by HaaLeo** [comment]
fixed with version v1.0.0
